name: "acumatica_data_platform"
version: "1.0.0"
config-version: 2

profile: "data_platform"

# Paths ----------------------------------------------------------------------
model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

# Project‑wide variables ------------------------------------------------------
vars:
  start_date: "2019-01-01"
  bronze_schema: "bronze_repsly"   # still available for any model‑level var() calls
  silver_schema: "silver_repsly"

# Model configuration --------------------------------------------------------
models:
  acumatica_data_platform:

    # ────────────────────  BRONZE (raw)  ────────────────────
    raw:
      +materialized: view
      acumatica:
        +database: bronze_acumatica
      repsly:
        +database: bronze_repsly

    # ────────────────────  SILVER (curated)  ────────────────────
    curated:
      +materialized: table
      acumatica:
        +database: silver_acumatica
      repsly:
        +database: silver_repsly

    # ────────────────────  GOLD (analytics)  ────────────────────
    analytics:
      +materialized: table
      +schema: gold_unified
