# dbt_project.yml
name: 'acumatica_data_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'data_platform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"] 
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models - UPDATED WITH PROPER SCHEMAS
models:
  acumatica_data_platform:
    # BRONZE LAYER: Raw data from sources
    raw:
      +materialized: view
      # Source-specific schemas for bronze layer
      acumatica:
        +schema: bronze_acumatica
      repsly:
        +schema: bronze_repsly  # Future: when you add Repsly
    
    # SILVER LAYER: Cleaned, validated business data  
    curated:
      +materialized: table
      # Source-specific schemas for silver layer
      acumatica:
        +schema: silver_acumatica
      repsly:
        +schema: silver_repsly  # Future: when you add Repsly
    
    # GOLD LAYER: Cross-source business logic (future)
    analytics:
      +materialized: table
      +schema: gold_unified  # Future: cross-source analytics

# Variables
vars:
  # Override this in your profiles.yml or from the command line
  start_date: '2019-01-01'