data_platform:
  outputs:
    dev:
      connect_timeout: 10
      dbname: airflow
      host: postgres
      keepalives_idle: 0
      password: postgres
      port: 5432
      retries: 1
      schema: public
      threads: 4
      type: postgres
      user: postgres
    prod:
      connect_timeout: 10
      dbname: airflow
      host: postgres
      keepalives_idle: 0
      password: postgres
      port: 5432
      retries: 1
      schema: public
      threads: 4
      type: postgres
      user: postgres
  target: dev
