data_platform:
  outputs:
    dev:
      connection_timeout: 20
      host: gxsbrpbg6w.us-east1.gcp.clickhouse.cloud
      password: 7A8UdbJ4V~7w8
      port: 8443
      receive_timeout: 300
      schema: default
      secure: true
      send_timeout: 300
      threads: 4
      type: clickhouse
      user: default
    prod:
      connection_timeout: 20
      host: gxsbrpbg6w.us-east1.gcp.clickhouse.cloud
      password: 7A8UdbJ4V~7w8
      port: 8443
      receive_timeout: 300
      schema: default
      secure: true
      send_timeout: 300
      threads: 4
      type: clickhouse
      user: default
  target: dev
