-- customers_raw.sql
-- Raw customer data (bronze layer) - append-only view over landing table
-- Retains original column naming (mapped to *_raw where appropriate)
-- NOTE: Source points to acumatica_raw.raw_customers (created by ingestion)

{{ config(materialized='view') }}

SELECT 
    id                                AS customer_guid,
    "rowNumber"::TEXT                 AS row_number,
    note::TEXT                        AS note,
    "AccountRef"::TEXT                AS account_ref,
    "ApplyOverdueCharges"::TEXT       AS apply_overdue_charges_raw,
    "AutoApplyPayments"::TEXT         AS auto_apply_payments_raw,
    "BAccountID"::TEXT                AS b_account_id,
    "BillingAddressOverride"::TEXT    AS billing_address_override_raw,
    "BillingContactOverride"::TEXT    AS billing_contact_override_raw,
    "CreatedDateTime"::TEXT           AS created_datetime_raw,
    "CreditLimit"::TEXT               AS credit_limit_raw,
    "CurrencyID"::TEXT                AS currency_id,
    "CurrencyRateType"::TEXT          AS currency_rate_type,
    "CustomerCategory"::TEXT          AS customer_category,
    "CustomerClass"::TEXT             AS customer_class,
    "CustomerID"::TEXT                AS customer_id,
    "CustomerName"::TEXT              AS customer_name,
    "Email"::TEXT                     AS email_raw,
    "EnableCurrencyOverride"::TEXT    AS enable_currency_override_raw,
    "EnableRateOverride"::TEXT        AS enable_rate_override_raw,
    "EnableWriteOffs"::TEXT           AS enable_write_offs_raw,
    "FOBPoint"::TEXT                  AS fob_point,
    "LastModifiedDateTime"::TEXT      AS last_modified_datetime_raw,
    "LeadTimedays"::TEXT              AS lead_time_days_raw,
    "LocationName"::TEXT              AS location_name,
    "MultiCurrencyStatements"::TEXT   AS multi_currency_statements_raw,
    "NoteID"::TEXT                    AS note_id,
    "OrderPriority"::TEXT             AS order_priority_raw,
    "ParentRecord"::TEXT              AS parent_record,
    "PriceClassID"::TEXT              AS price_class_id,
    "PrimaryContactID"::TEXT          AS primary_contact_id_raw,
    "PrintDunningLetters"::TEXT       AS print_dunning_letters_raw,
    "PrintInvoices"::TEXT             AS print_invoices_raw,
    "PrintStatements"::TEXT           AS print_statements_raw,
    "ResidentialDelivery"::TEXT       AS residential_delivery_raw,
    "SaturdayDelivery"::TEXT          AS saturday_delivery_raw,
    "SendDunningLettersbyEmail"::TEXT AS send_dunning_letters_by_email_raw,
    "SendInvoicesbyEmail"::TEXT       AS send_invoices_by_email_raw,
    "SendStatementsbyEmail"::TEXT     AS send_statements_by_email_raw,
    "ShippingAddressOverride"::TEXT   AS shipping_address_override_raw,
    "ShippingBranch"::TEXT            AS shipping_branch,
    "ShippingContactOverride"::TEXT   AS shipping_contact_override_raw,
    "ShippingRule"::TEXT              AS shipping_rule,
    "ShippingTerms"::TEXT             AS shipping_terms,
    "ShippingZoneID"::TEXT            AS shipping_zone_id,
    "ShipVia"::TEXT                   AS ship_via,
    "StatementCycleID"::TEXT          AS statement_cycle_id,
    "StatementType"::TEXT             AS statement_type,
    "Status"::TEXT                    AS status,
    "TaxRegistrationID"::TEXT         AS tax_registration_id,
    "TaxZone"::TEXT                   AS tax_zone,
    "Terms"::TEXT                     AS payment_terms,
    "WarehouseID"::TEXT               AS warehouse_id,
    "WriteOffLimit"::TEXT             AS write_off_limit_raw,
    custom::TEXT                      AS custom_json_raw,
    "_links"::TEXT                    AS source_links,
    "_extracted_at"                   AS extracted_at,
    "_source_system"                  AS source_system,
    "_endpoint"                       AS endpoint
FROM {{ source('acumatica_raw', 'raw_customers') }}
WHERE "CustomerID" IS NOT NULL
