-- models/bronze/stock_items_raw.sql
-- Raw stock items data (bronze layer) – append-only source view
-- KEEP every landed row; no dedup here. Upstream incremental extraction limits volume.
{{ config(materialized='view') }}

SELECT 
    id as stock_item_guid,
    "rowNumber"::TEXT as row_number,
    note::TEXT,
    "ABCCode"::TEXT as abc_code,
    "AutoIncrementalValue"::TEXT as auto_incremental_value_raw,
    "Availability"::TEXT as availability,
    "BaseUOM"::TEXT as base_uom,
    "COGSAccount"::TEXT as cogs_account,
    "COGSSubaccount"::TEXT as cogs_subaccount,
    "Content"::TEXT as content,
    "CountryOfOrigin"::TEXT as country_of_origin,
    "CurrentStdCost"::TEXT as current_std_cost_raw,
    "CurySpecificMSRP"::TEXT as cury_specific_msrp_raw,
    "CurySpecificPrice"::TEXT as cury_specific_price_raw,
    "DefaultIssueLocationID"::TEXT as default_issue_location_id,
    "DefaultPrice"::TEXT as default_price_raw,
    "DefaultReceiptLocationID"::TEXT as default_receipt_location_id,
    "DefaultWarehouseID"::TEXT as default_warehouse_id,
    "Description"::TEXT as description,
    "DimensionVolume"::TEXT as dimension_volume_raw,
    "DimensionWeight"::TEXT as dimension_weight_raw,
    "DiscountAccount"::TEXT as discount_account,
    "DiscountSubaccount"::TEXT as discount_subaccount,
    "ImageUrl"::TEXT as image_url,
    "InventoryAccount"::TEXT as inventory_account,
    "InventoryID"::TEXT as inventory_id,
    "InventorySubaccount"::TEXT as inventory_subaccount,
    "IsAKit"::TEXT as is_a_kit_raw,
    "ItemClass"::TEXT as item_class,
    "ItemStatus"::TEXT as item_status,
    "ItemType"::TEXT as item_type,
    "LandedCostVarianceAccount"::TEXT as landed_cost_variance_account,
    "LandedCostVarianceSubaccount"::TEXT as landed_cost_variance_subaccount,
    "LastModified"::TEXT as last_modified_raw,
    "LastStdCost"::TEXT as last_std_cost_raw,
    "LotSerialClass"::TEXT as lot_serial_class,
    "Markup"::TEXT as markup_raw,
    "MinMarkup"::TEXT as min_markup_raw,
    "MSRP"::TEXT as msrp_raw,
    "NotAvailable"::TEXT as not_available,
    "NoteID"::TEXT as note_id,
    "PendingStdCost"::TEXT as pending_std_cost_raw,
    "POAccrualAccount"::TEXT as po_accrual_account,
    "POAccrualSubaccount"::TEXT as po_accrual_subaccount,
    "PostingClass"::TEXT as posting_class,
    "PriceClass"::TEXT as price_class,
    "PriceManager"::TEXT as price_manager,
    "PriceWorkgroup"::TEXT as price_workgroup,
    "ProductManager"::TEXT as product_manager,
    "ProductWorkgroup"::TEXT as product_workgroup,
    "PurchasePriceVarianceAccount"::TEXT as purchase_price_variance_account,
    "PurchasePriceVarianceSubaccount"::TEXT as purchase_price_variance_subaccount,
    "PurchaseUOM"::TEXT as purchase_uom,
    "ReasonCodeSubaccount"::TEXT as reason_code_subaccount,
    "SalesAccount"::TEXT as sales_account,
    "SalesSubaccount"::TEXT as sales_subaccount,
    "SalesUOM"::TEXT as sales_uom,
    "StandardCostRevaluationAccount"::TEXT as standard_cost_revaluation_account,
    "StandardCostRevaluationSubaccount"::TEXT as standard_cost_revaluation_subaccount,
    "StandardCostVarianceAccount"::TEXT as standard_cost_variance_account,
    "StandardCostVarianceSubaccount"::TEXT as standard_cost_variance_subaccount,
    "SubjectToCommission"::TEXT as subject_to_commission_raw,
    "TariffCode"::TEXT as tariff_code,
    "TaxCategory"::TEXT as tax_category,
    "ValuationMethod"::TEXT as valuation_method,
    "Visibility"::TEXT as visibility,
    "VolumeUOM"::TEXT as volume_uom,
    "WeightUOM"::TEXT as weight_uom,
    custom::TEXT,
    "_links"::TEXT as source_links,
    "_extracted_at" as extracted_at,
    "_source_system" as source_system,
    "_endpoint" as endpoint
FROM {{ source('acumatica_raw', 'raw_stock_items') }}
WHERE "InventoryID" IS NOT NULL
