-- Raw stock items data with basic filtering and renaming
{{ config(materialized='view') }}

SELECT 
    id as item_guid,
    "InventoryID"::TEXT as inventory_id,
    "Description"::TEXT as description,
    "ItemClass"::TEXT as item_class,
    "ItemType"::TEXT as item_type,
    "ItemStatus"::TEXT as item_status,
    "DefaultPrice"::TEXT as default_price_raw,
    "CurrentStdCost"::TEXT as current_std_cost_raw,
    "LastStdCost"::TEXT as last_std_cost_raw,
    "PendingStdCost"::TEXT as pending_std_cost_raw,
    "MSRP"::TEXT as msrp_raw,
    "CurySpecificMSRP"::TEXT as specific_msrp_raw,
    "CurySpecificPrice"::TEXT as specific_price_raw,
    "Markup"::TEXT as markup_raw,
    "MinMarkup"::TEXT as min_markup_raw,
    "BaseUOM"::TEXT as base_uom,
    "PurchaseUOM"::TEXT as purchase_uom,
    "SalesUOM"::TEXT as sales_uom,
    "VolumeUOM"::TEXT as volume_uom,
    "WeightUOM"::TEXT as weight_uom,
    "DimensionVolume"::TEXT as dimension_volume_raw,
    "DimensionWeight"::TEXT as dimension_weight_raw,
    "LastModified"::TEXT as last_modified_raw,
    "DefaultWarehouseID"::TEXT as default_warehouse_id,
    "DefaultIssueLocationID"::TEXT as default_issue_location_id,
    "DefaultReceiptLocationID"::TEXT as default_receipt_location_id,
    "PostingClass"::TEXT as posting_class,
    "LotSerialClass"::TEXT as lot_serial_class,
    "PriceClass"::TEXT as price_class,
    "ValuationMethod"::TEXT as valuation_method,
    "TaxCategory"::TEXT as tax_category,
    "CountryOfOrigin"::TEXT as country_of_origin,
    "TariffCode"::TEXT as tariff_code,
    "ABCCode"::TEXT as abc_code,
    "Availability"::TEXT as availability,
    "Visibility"::TEXT as visibility,
    "IsAKit"::TEXT as is_a_kit_raw,
    "SubjectToCommission"::TEXT as subject_to_commission_raw,
    "NotAvailable"::TEXT as not_available_raw,
    "AutoIncrementalValue"::TEXT as auto_incremental_value_raw,
    "Content"::TEXT as content,
    "ImageUrl"::TEXT as image_url,
    note::TEXT,
    custom::TEXT,
    "_links"::TEXT as source_links,
    "_extracted_at" as extracted_at,
    "_source_system" as source_system,
    "_endpoint" as endpoint

FROM {{ source('acumatica_raw', 'raw_stock_items') }}
WHERE "InventoryID" IS NOT NULL