-- Raw vendors data with basic filtering and renaming
-- dbt/models/raw/acumatica/vendors_raw.sql

{{ config(materialized='view') }}

SELECT
    "id"::TEXT as vendor_id,
    "rowNumber"::TEXT as row_number,
    "note"::TEXT as note,
    "AccountRef"::TEXT as account_ref,
    "APAccount"::TEXT as ap_account,
    "APSubaccount"::TEXT as ap_subaccount,
    "CashAccount"::TEXT as cash_account,
    "CreatedDateTime"::TEXT as created_datetime_raw,
    "CurrencyID"::TEXT as currency_id,
    "CurrencyRateType"::TEXT as currency_rate_type,
    "EnableCurrencyOverride"::TEXT as enable_currency_override_raw,
    "EnableRateOverride"::TEXT as enable_rate_override_raw,
    "F1099Box"::TEXT as f1099_box,
    "F1099Vendor"::TEXT as f1099_vendor_raw,
    "FATCA"::TEXT as fatca,
    "FOBPoint"::TEXT as fob_point,
    "ForeignEntity"::TEXT as foreign_entity_raw,
    "LandedCostVendor"::TEXT as landed_cost_vendor_raw,
    "LastModifiedDateTime"::TEXT as last_modified_datetime_raw,
    "LeadTimedays"::TEXT as lead_time_days_raw,
    "LegalName"::TEXT as legal_name,
    "LocationName"::TEXT as location_name,
    "MaxReceipt"::TEXT as max_receipt_raw,
    "MinReceipt"::TEXT as min_receipt_raw,
    "ParentAccount"::TEXT as parent_account,
    "PaymentBy"::TEXT as payment_by,
    "PaymentLeadTimedays"::TEXT as payment_lead_time_days_raw,
    "PaymentMethod"::TEXT as payment_method,
    "PaySeparately"::TEXT as pay_separately_raw,
    "PrintOrders"::TEXT as print_orders_raw,
    "ReceiptAction"::TEXT as receipt_action,
    "ReceivingBranch"::TEXT as receiving_branch,
    "RemittanceAddressOverride"::TEXT as remittance_address_override_raw,
    "RemittanceContactOverride"::TEXT as remittance_contact_override_raw,
    "SendOrdersbyEmail"::TEXT as send_orders_by_email_raw,
    "ShippingAddressOverride"::TEXT as shipping_address_override_raw,
    "ShippingContactOverride"::TEXT as shipping_contact_override_raw,
    "ShippingTerms"::TEXT as shipping_terms,
    "ShipVia"::TEXT as ship_via,
    "Status"::TEXT as status_raw,
    "TaxRegistrationID"::TEXT as tax_registration_id,
    "TaxZone"::TEXT as tax_zone,
    "Terms"::TEXT as terms,
    "ThresholdReceipt"::TEXT as threshold_receipt_raw,
    "VendorClass"::TEXT as vendor_class,
    "VendorID"::TEXT as vendor_code,
    "VendorIsLaborUnion"::TEXT as vendor_is_labor_union_raw,
    "VendorIsTaxAgency"::TEXT as vendor_is_tax_agency_raw,
    "VendorName"::TEXT as vendor_name,
    "Warehouse"::TEXT as warehouse,
    "custom"::TEXT as custom_raw,
    "_links"::TEXT as links_raw,
    "_extracted_at" as extracted_at,
    "_source_system" as source_system,
    "_endpoint" as endpoint

FROM {{ source('acumatica_raw', 'raw_vendors') }}
WHERE "id" IS NOT NULL