-- models/bronze/vendors_raw.sql
-- Raw vendor data (bronze layer) – append-only view over landing table
{{ config(materialized='view') }}

SELECT 
    id                                   AS vendor_guid,
    "rowNumber"::TEXT                     AS row_number,
    note::TEXT,
    "AccountRef"::TEXT                    AS account_ref,
    "APAccount"::TEXT                     AS ap_account,
    "APSubaccount"::TEXT                  AS ap_subaccount,
    "CashAccount"::TEXT                   AS cash_account,
    "CreatedDateTime"::TEXT               AS created_datetime_raw,
    "CurrencyID"::TEXT                    AS currency_id,
    "CurrencyRateType"::TEXT              AS currency_rate_type,
    "EnableCurrencyOverride"::TEXT        AS enable_currency_override_raw,
    "EnableRateOverride"::TEXT            AS enable_rate_override_raw,
    "F1099Box"::TEXT                      AS f1099_box,
    "F1099Vendor"::TEXT                   AS f1099_vendor_raw,
    "FATCA"::TEXT                         AS fatca,
    "FOBPoint"::TEXT                      AS fob_point,
    "ForeignEntity"::TEXT                 AS foreign_entity_raw,
    "LandedCostVendor"::TEXT              AS landed_cost_vendor_raw,
    "LastModifiedDateTime"::TEXT          AS last_modified_datetime_raw,
    "LeadTimedays"::TEXT                  AS lead_time_days_raw,
    "LegalName"::TEXT                     AS legal_name,
    "LocationName"::TEXT                  AS location_name,
    "MaxReceipt"::TEXT                    AS max_receipt_raw,
    "MinReceipt"::TEXT                    AS min_receipt_raw,
    "ParentAccount"::TEXT                 AS parent_account,
    "PaymentBy"::TEXT                     AS payment_by,
    "PaymentLeadTimedays"::TEXT           AS payment_lead_time_days_raw,
    "PaymentMethod"::TEXT                 AS payment_method,
    "PaySeparately"::TEXT                 AS pay_separately_raw,
    "PrintOrders"::TEXT                   AS print_orders_raw,
    "ReceiptAction"::TEXT                 AS receipt_action,
    "ReceivingBranch"::TEXT               AS receiving_branch,
    "RemittanceAddressOverride"::TEXT     AS remittance_address_override_raw,
    "RemittanceContactOverride"::TEXT     AS remittance_contact_override_raw,
    "SendOrdersbyEmail"::TEXT             AS send_orders_by_email_raw,
    "ShippingAddressOverride"::TEXT       AS shipping_address_override_raw,
    "ShippingContactOverride"::TEXT       AS shipping_contact_override_raw,
    "ShippingTerms"::TEXT                 AS shipping_terms,
    "ShipVia"::TEXT                       AS ship_via,
    "Status"::TEXT                        AS status,
    "TaxRegistrationID"::TEXT             AS tax_registration_id,
    "TaxZone"::TEXT                       AS tax_zone,
    "Terms"::TEXT                         AS payment_terms,
    "ThresholdReceipt"::TEXT              AS threshold_receipt_raw,
    "VendorClass"::TEXT                   AS vendor_class,
    "VendorID"::TEXT                      AS vendor_code,
    "VendorIsLaborUnion"::TEXT            AS vendor_is_labor_union_raw,
    "VendorIsTaxAgency"::TEXT             AS vendor_is_tax_agency_raw,
    "VendorName"::TEXT                    AS vendor_name,
    "Warehouse"::TEXT                     AS warehouse,
    custom::TEXT,
    "_links"::TEXT                        AS source_links,
    "_extracted_at"                       AS extracted_at,
    "_source_system"                      AS source_system,
    "_endpoint"                           AS endpoint
FROM {{ source('acumatica_raw', 'raw_vendor') }}
WHERE "VendorID" IS NOT NULL
