warehouse:
  name: "ClickHouse"
  type: "clickhouse"
  
connection:
  host: "your-clickhouse.cloud"
  port: 9440
  database: "analytics_db"
  user: "default"
  password: "your_password"
  secure: true