warehouse:
  name: "ClickHouse"
  type: "clickhouse"
  
connection:
  host: "gxsbrpbg6w.us-east1.gcp.clickhouse.cloud"
  port: 8443
  database: "default"
  user: "default"
  password: "7A8UdbJ4V~7w8"
  secure: true
  # schema: "bronze_acumatica"