warehouse:
  name: "Snowflake"
  type: "snowflake"
  
connection:
  account: "your-account.snowflakecomputing.com"
  user: "your_username"
  password: "your_password"
  warehouse: "COMPUTE_WH"
  database: "ANALYTICS_DB"
  schema: "PUBLIC"
  role: "ACCOUNTADMIN"