# acumatica.yml - Configuration for Acumatica DAG (incremental enabled)

dag:
  dag_id: "acumatica_extract_transform"
  description: "Extract from Acumatica API and transform with dbt"
  owner: "data-team"
  schedule:
    type: "weekly"        # can switch to 'hourly' / 'daily'
    timezone: "UTC"
  max_active_runs: 1
  start_date: "2025-07-18"
  retries: 1
  retry_delay_minutes: 5
  email_on_failure: true
  email_on_retry: false
  email_on_success: true
  tags:
    - "acumatica"
    - "extract"
    - "transform"
    - "dbt"
    - "production"

notifications:
  email:
    failure_recipients:
      - "mustafa.zaki@mammoth.org"
    success_recipients:
      - "mustafa.zaki@mammoth.org"
    retry_recipients:
      - "mustafa.zaki@mammoth.org"

api:
  default_version: "23.200.001"
  entity_endpoint: "entity/Default"
  auth_endpoint: "entity/auth/login"
  rate_limiting:
    requests_per_second: 10
    max_retries: 3
    backoff_factor: 1.5
    timeout_seconds: 30
  pagination:
    default_page_size: 100
    max_page_size: 1000

extraction:
  mode: "testing"  # "testing" | "production"
  incremental:
    enabled: true
    default_timestamp_field: "LastModifiedDateTime"
    lookback_minutes: 5
    full_refresh_days: 7          # (can be used later to trigger forced full)
    state_path: "/opt/airflow/state/acumatica_watermarks.json"
  testing:
    max_records_per_endpoint: 100
  production:
    max_records_per_endpoint: null
  paths:
    raw_data_directory: "/opt/airflow/data/raw/acumatica"

  endpoints:
    customers:
      path: "Customer"
      enabled: true
      priority: "high"
      schedule:
        times: ["00:00", "06:00", "12:00", "18:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
    sales_invoices:
      path: "SalesInvoice"
      enabled: true
      schedule:
        times: ["01:00", "05:00", "09:00", "13:00", "17:00", "21:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        require_validation: true
    sales_orders:
      path: "SalesOrder"
      enabled: true
      schedule:
        times: ["02:00", "10:00", "18:00"]
      custom:
        incremental: true
    stock_items:
      path: "StockItem"
      enabled: true
      schedule:
        times: ["03:00"]
      custom:
        incremental: true
        max_pages: 50
    bill:
      path: "Bill"
      enabled: true
      custom:
        incremental: true
    vendor:
      path: "Vendor"
      enabled: true
      custom:
        incremental: true
    purchase_order:
      path: "PurchaseOrder"
      enabled: true
      custom:
        incremental: true

warehouse:
  active_warehouse: "clickhouse"
  schemas:
    bronze_schema: "default_bronze_acumatica"
    silver_schema: "default_silver_acumatica"
    raw_schema: "default_bronze_acumatica"
    staging_schema: "default_silver_acumatica"

dbt:
  project_dir: "/opt/airflow/dbt"
  profiles_dir: "/opt/airflow/dbt"
  execution:
    fail_fast: false
    full_refresh: false
    threads: 4
