# acumatica.yml - Configuration for Acumatica DAG (incremental enabled, fixed)

dag:
  dag_id: "acumatica_extract_transform"
  description: "Extract from Acumatica API and transform with dbt (incremental)"
  owner: "data-team"
  schedule:
    type: "daily"        # hourly | daily | weekly | monthly | manual | cron
    time: "02:00"        # For daily/weekly/monthly schedules
    timezone: "UTC"
  max_active_runs: 1
  start_date: "2025-07-18"
  retries: 2
  retry_delay_minutes: 5
  email_on_failure: true
  email_on_retry: false
  email_on_success: true
  tags:
    - "acumatica"
    - "extract"
    - "transform"
    - "dbt"
    - "incremental"

notifications:
  email:
    failure_recipients:
      - "mustafa.zaki@mammoth.org"
    success_recipients:
      - "mustafa.zaki@mammoth.org"
    retry_recipients:
      - "mustafa.zaki@mammoth.org"

api:
  default_version: "23.200.001"
  entity_endpoint: "entity/Default"
  auth_endpoint: "entity/auth/login"
  rate_limiting:
    requests_per_second: 8        # Conservative rate limit
    max_retries: 3
    backoff_factor: 2.0          # Exponential backoff
    timeout_seconds: 60          # Increased timeout
  pagination:
    default_page_size: 100
    max_page_size: 1000

extraction:
  mode: "production"  # "testing" | "production"
  incremental:
    enabled: true
    default_timestamp_field: "LastModifiedDateTime"
    lookback_minutes: 10         # Increased lookback for safety
    full_refresh_days: 30        # Trigger full refresh every 30 days
    state_path: "/opt/airflow/state/acumatica_watermarks.json"
  testing:
    max_records_per_endpoint: 50
  production:
    max_records_per_endpoint: null
  paths:
    raw_data_directory: "/opt/airflow/data/raw/acumatica"

  endpoints:
    # High-frequency endpoints (multiple times per day)
    sales_invoices:
      path: "api/odata/dac/SOInvoice"
      enabled: true
      priority: "high"
      schedule:
        times: ["02:00", "08:00", "14:00", "20:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 200
    
    bill:
      path: "Bill"
      enabled: true
      priority: "high"
      schedule:
        times: ["02:30", "08:30", "14:30", "20:30"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 200
    
    sales_orders:
      path: "api/odata/dac/SOOrder"
      enabled: true
      priority: "medium"
      # schedule:
      #   times: ["03:00", "09:00", "15:00", "21:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 150
    
    purchase_order:
      path: "PurchaseOrder"
      enabled: true
      priority: "medium"
      schedule:
        times: ["03:30", "09:30", "15:30", "21:30"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 150
    
    # Medium-frequency endpoints (daily)
    customers:
      path: "Customer"
      enabled: true
      priority: "medium"
      schedule:
        times: ["04:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 100
    
    vendor:
      path: "Vendor"
      enabled: true
      priority: "medium"
      schedule:
        times: ["04:30"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 100
    
    # Low-frequency endpoints (less frequent updates)
    stock_items:
      path: "StockItem"
      enabled: true
      priority: "low"
      schedule:
        times: ["05:00"]
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
        max_pages: 300
    
    # Additional endpoints (can be enabled as needed)
    purchase_receipts:
      path: "PurchaseReceipt"
      enabled: false
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
    
    shipments:
      path: "Shipment"
      enabled: false
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"
    
    payments:
      path: "Payment"
      enabled: false
      custom:
        incremental: true
        timestamp_field: "LastModifiedDateTime"

warehouse:
  active_warehouse: "clickhouse"
  schemas:
    bronze_schema: "acumatica_bronze"
    silver_schema: "acumatica_silver"
    raw_schema: "acumatica_bronze"      # Alias for compatibility
    staging_schema: "acumatica_silver"  # Alias for compatibility

dbt:
  project_dir: "/opt/airflow/dbt"
  profiles_dir: "/opt/airflow/dbt"
  execution:
    fail_fast: false
    full_refresh: false
    threads: 4
    
# Data quality settings
data_quality:
  enabled: true
  checks:
    - type: "row_count"
      threshold_min: 0
    - type: "freshness"
      max_age_hours: 24
    - type: "null_check"
      critical_columns: ["id", "LastModifiedDateTime"]